/**
 * Seed data for FTC: Nihon app
 * Data extracted from: Docs/japan trip details/Blaalid_Rowles_Japan_Itinerary_March_2026_UPDATED.md
 */

import type { Activity, Accommodation, TransitSegment } from '@/types/database';

// Helper to generate UUIDs (simple version for seed data)
let idCounter = 0;
const genId = (prefix: string) => `${prefix}-${String(++idCounter).padStart(4, '0')}`;

const now = new Date().toISOString();

// ============================================================================
// ACCOMMODATIONS
// ============================================================================

export const accommodations: Accommodation[] = [
  {
    id: genId('acc'),
    name: '&Here Shinjuku',
    address: '2-15-14-2 Shinjuku, Shinjuku City, Tokyo 160-0022, Japan',
    addressJp: '〒160-0022 東京都新宿区新宿2-15-14-2',
    checkInTime: '15:00',
    checkOutTime: '11:00',
    confirmationNumber: '5464976388',
    pinCode: '5562',
    phone: '+81 3-6384-2040',
    googleMapsUrl: 'https://maps.google.com/?q=&Here+Shinjuku',
    instructions: `Check-in: 3:00 PM - 10:00 PM. From Haneda: Airport Limousine Bus to "Busta Shinjuku" (~50 min), then 14-min walk. Cash NOT accepted for payment.`,
    startDate: '2026-03-07',
    endDate: '2026-03-12',
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('acc'),
    name: 'Takumino yado Yoshimatsu Ryokan',
    address: '521 Hakone, Hakone-machi, Ashigarashimo-gun, Kanagawa Prefecture 250-0521, Japan',
    addressJp: '〒250-0521 神奈川県足柄下郡箱根町箱根521',
    checkInTime: '15:00',
    checkOutTime: '11:00',
    confirmationNumber: 'XEVXZWUZ / 9SPM1U1T',
    pinCode: null,
    phone: '0460-83-6661',
    googleMapsUrl: 'https://maps.google.com/?q=Takumino+yado+Yoshimatsu',
    instructions: `CRITICAL: Call ahead (0460-83-6661) to arrange pickup from Hakonemachi Port Pier (Pirate Ship landing). Pickup 3-5 PM. Drop-off 8-11 AM to same location. Kaiseki dinner served in room 6-7 PM.`,
    startDate: '2026-03-12',
    endDate: '2026-03-14',
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('acc'),
    name: 'Fujinoma Machiya House',
    address: '476-11 Tenshitsukinuke 4chome, Shimogyo Ward, Kyoto 600-8456, Japan',
    addressJp: '〒600-8456 京都市下京区天使突抜4丁目476-11',
    checkInTime: '15:00',
    checkOutTime: '10:00',
    confirmationNumber: '6306540803',
    pinCode: '5278',
    phone: '+81 90-8161-3870',
    googleMapsUrl: 'https://g.page/machiya-inns-hotels',
    instructions: `NOT at the house! Go to MACHIYA INNS Check-in Desk first (685-2 Higashishiokōjichō, 3-min from Kyoto Station). Hours: 10 AM - 7 PM. PAY ACCOMMODATION TAX ¥8,400 CASH at check-in desk.`,
    startDate: '2026-03-14',
    endDate: '2026-03-17',
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('acc'),
    name: 'MIMARU Osaka Shinsaibashi East',
    address: '1-7-9 Higashishinsaibashi, Chuo-ku, Osaka 542-0083, Japan',
    addressJp: '〒542-0083 大阪市中央区東心斎橋1-7-9',
    checkInTime: '15:00',
    checkOutTime: '11:00',
    confirmationNumber: '5937762447',
    pinCode: '7761',
    phone: '+81 6-4256-4010',
    googleMapsUrl: 'https://maps.google.com/?q=MIMARU+Osaka+Shinsaibashi+East',
    instructions: `Check-in: 3:00 PM - 10:00 PM. FULLY PAID. Walking distance to Dotonbori, Shinsaibashi shopping. Near Namba Station.`,
    startDate: '2026-03-17',
    endDate: '2026-03-21',
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
];

// ============================================================================
// ACTIVITIES - Day by Day
// ============================================================================

export const activities: Activity[] = [
  // -------------------------------------------------------------------------
  // Day 1: Saturday, March 7 - Arrival in Tokyo
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 1,
    date: '2026-03-07',
    startTime: '15:20',
    durationMinutes: 40,
    name: 'Arrive Tokyo Haneda',
    category: 'transit',
    locationName: 'Haneda Airport Terminal 3',
    locationAddress: 'Haneda Airport, Tokyo, Japan',
    locationAddressJp: null,
    locationLat: 35.5494,
    locationLng: 139.7798,
    googleMapsUrl: 'https://maps.google.com/?q=Haneda+Airport+Terminal+3',
    websiteUrl: null,
    description: 'Flight DL0121 arrives. Immigration & customs, collect luggage.',
    tips: 'Have passport and customs form ready. Follow signs to arrivals.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 1,
    date: '2026-03-07',
    startTime: '16:30',
    durationMinutes: 50,
    name: 'Airport Limousine Bus to Shinjuku',
    category: 'transit',
    locationName: 'Haneda Airport Limousine Bus Counter',
    locationAddress: 'Arrivals floor, Haneda Terminal 3',
    locationAddressJp: null,
    locationLat: 35.5494,
    locationLng: 139.7798,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Take bus to Busta Shinjuku (~50 min). Cost: ¥3,000-4,500 per person.',
    tips: 'Buses depart every 20-30 minutes. Buy ticket at counter.',
    whatToOrder: null,
    backupAlternative: 'Keikyu Line + Tokyo Metro (faster but more transfers)',
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 1,
    date: '2026-03-07',
    startTime: '18:00',
    durationMinutes: 30,
    name: 'Check-in at &Here Shinjuku',
    category: 'hotel',
    locationName: '&Here Shinjuku',
    locationAddress: '2-15-14-2 Shinjuku, Shinjuku City, Tokyo',
    locationAddressJp: '〒160-0022 東京都新宿区新宿2-15-14-2',
    locationLat: 35.6917,
    locationLng: 139.7043,
    googleMapsUrl: 'https://maps.google.com/?q=&Here+Shinjuku',
    websiteUrl: 'https://andherehotels-shinjuku.com/en/',
    description: '14-min walk from Busta Shinjuku. Confirmation: 5464976388, PIN: 5562',
    tips: 'Check-in until 10 PM. Cash NOT accepted.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 1,
    date: '2026-03-07',
    startTime: '19:00',
    durationMinutes: 60,
    name: 'Easy Dinner Near Hotel',
    category: 'food',
    locationName: 'Near &Here Shinjuku',
    locationAddress: 'Shinjuku area',
    locationAddressJp: null,
    locationLat: 35.6917,
    locationLng: 139.7043,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Light dinner - convenience store or simple restaurant. Try to stay awake until 9-10 PM for jetlag.',
    tips: '7-Eleven and Lawson have great food. Onigiri, sandwiches, hot foods.',
    whatToOrder: 'Onigiri, nikuman (steamed bun), hot coffee',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 2: Sunday, March 8 - Tokyo Day 1
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 2,
    date: '2026-03-08',
    startTime: '08:00',
    durationMinutes: 60,
    name: 'Breakfast',
    category: 'food',
    locationName: 'Near hotel or 7-Eleven',
    locationAddress: 'Shinjuku area',
    locationAddressJp: null,
    locationLat: 35.6917,
    locationLng: 139.7043,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Grab breakfast at convenience store or nearby market.',
    tips: 'Japanese convenience store food is surprisingly good!',
    whatToOrder: 'Onigiri, egg sandwich, hot coffee',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 2,
    date: '2026-03-08',
    startTime: '09:00',
    durationMinutes: 180,
    name: 'Asakusa - Senso-ji Temple',
    category: 'temple',
    locationName: 'Senso-ji Temple',
    locationAddress: '2-3-1 Asakusa, Taito City, Tokyo',
    locationAddressJp: '〒111-0032 東京都台東区浅草2-3-1',
    locationLat: 35.7148,
    locationLng: 139.7967,
    googleMapsUrl: 'https://maps.google.com/?q=Senso-ji+Temple',
    websiteUrl: null,
    description: "Tokyo's oldest temple (628 AD). See Kaminarimon Gate, Nakamise-dori shopping street, Azumabashi Bridge.",
    tips: 'Arrive early to avoid crowds. Nakamise-dori has great snacks and souvenirs.',
    whatToOrder: 'Melon pan, ningyo-yaki (small cakes)',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 2,
    date: '2026-03-08',
    startTime: '12:00',
    durationMinutes: 120,
    name: 'Tokyo Skytree & Solamachi',
    category: 'activity',
    locationName: 'Tokyo Skytree',
    locationAddress: '1-1-2 Oshiage, Sumida City, Tokyo',
    locationAddressJp: '〒131-0045 東京都墨田区押上1-1-2',
    locationLat: 35.7101,
    locationLng: 139.8107,
    googleMapsUrl: 'https://maps.google.com/?q=Tokyo+Skytree',
    websiteUrl: 'https://www.tokyo-skytree.jp/en/',
    description: "634m tall - Japan's tallest structure. Tembo Deck (350m) observation. Solamachi Mall below for shopping & lunch.",
    tips: 'Book tickets online to skip lines. Clear days have Mt. Fuji views.',
    whatToOrder: null,
    backupAlternative: 'Skip observation deck, just explore Solamachi Mall',
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 2,
    date: '2026-03-08',
    startTime: '14:00',
    durationMinutes: 180,
    name: 'Ueno Park & Ameyoko Market',
    category: 'shopping',
    locationName: 'Ueno Park',
    locationAddress: 'Uenokoen, Taito City, Tokyo',
    locationAddressJp: '〒110-0007 東京都台東区上野公園',
    locationLat: 35.7146,
    locationLng: 139.7732,
    googleMapsUrl: 'https://maps.google.com/?q=Ueno+Park',
    websiteUrl: null,
    description: 'Museums, temples, zoo. Ameyoko Market - bustling shopping street under train tracks.',
    tips: 'Ameyoko is great for snacks, clothes, souvenirs. Bargaining sometimes works.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 2,
    date: '2026-03-08',
    startTime: '17:00',
    durationMinutes: 240,
    name: 'Akihabara Evening',
    category: 'activity',
    locationName: 'Akihabara',
    locationAddress: 'Akihabara, Chiyoda City, Tokyo',
    locationAddressJp: null,
    locationLat: 35.7023,
    locationLng: 139.7745,
    googleMapsUrl: 'https://maps.google.com/?q=Akihabara+Station',
    websiteUrl: null,
    description: 'Animal cafes (Microteacup, Bunny), Super Potato retro gaming, manga/capsule stores.',
    tips: 'Super Potato has 5 floors of retro games. Animal cafes need reservations sometimes.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 2,
    date: '2026-03-08',
    startTime: '19:00',
    durationMinutes: 90,
    name: 'Dinner - Yuzuan or Syabu-Yō',
    category: 'food',
    locationName: 'Akihabara',
    locationAddress: 'Akihabara area',
    locationAddressJp: null,
    locationLat: 35.7023,
    locationLng: 139.7745,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Yuzuan: All-you-can-eat sushi & A5 wagyu (gluten-free options). Syabu-Yō: Shabu-shabu with robot servers.',
    tips: 'Syabu-Yō is especially fun for kids with robot tablet ordering.',
    whatToOrder: 'A5 wagyu at Yuzuan, or shabu-shabu hotpot at Syabu-Yō',
    backupAlternative: 'Ramen shops in the area',
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 3: Monday, March 9 - Tokyo Day 2 (Big 3 Districts)
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 3,
    date: '2026-03-09',
    startTime: '09:00',
    durationMinutes: 240,
    name: 'Harajuku - Meiji Shrine & Takeshita Street',
    category: 'temple',
    locationName: 'Meiji Jingu Shrine',
    locationAddress: '1-1 Yoyogikamizonocho, Shibuya City, Tokyo',
    locationAddressJp: '〒151-8557 東京都渋谷区代々木神園町1-1',
    locationLat: 35.6764,
    locationLng: 139.6993,
    googleMapsUrl: 'https://maps.google.com/?q=Meiji+Jingu+Shrine',
    websiteUrl: null,
    description: 'Sacred forest, peaceful shrine. Then Takeshita Street for youth culture, kawaii shops, crepes. Optional hedgehog cafe.',
    tips: 'Meiji Shrine is very peaceful. Takeshita Street gets crowded afternoon.',
    whatToOrder: 'Crepes on Takeshita Street',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 3,
    date: '2026-03-09',
    startTime: '13:00',
    durationMinutes: 240,
    name: 'Shibuya - Crossing, Nintendo & Pokemon',
    category: 'shopping',
    locationName: 'Shibuya Crossing',
    locationAddress: 'Shibuya, Tokyo',
    locationAddressJp: null,
    locationLat: 35.6595,
    locationLng: 139.7004,
    googleMapsUrl: 'https://maps.google.com/?q=Shibuya+Crossing',
    websiteUrl: null,
    description: "World's busiest intersection, Hachiko Statue, Nintendo Store, Pokemon Store.",
    tips: 'Best view of crossing from Starbucks 2nd floor. Nintendo Store has playable demos.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 3,
    date: '2026-03-09',
    startTime: '17:00',
    durationMinutes: 120,
    name: 'Nonbei Yokocho',
    category: 'activity',
    locationName: "Nonbei Yokocho (Drunkard's Alley)",
    locationAddress: 'Near Shibuya Station',
    locationAddressJp: null,
    locationLat: 35.6595,
    locationLng: 139.7004,
    googleMapsUrl: 'https://maps.google.com/?q=Nonbei+Yokocho+Shibuya',
    websiteUrl: null,
    description: 'Atmospheric narrow alley with tiny bars. Visit when lanterns turn on at dusk.',
    tips: 'Great for photos. Most bars are very small (2-5 seats).',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: false,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 3,
    date: '2026-03-09',
    startTime: '19:00',
    durationMinutes: 180,
    name: 'Shinjuku Evening - Kabukicho & Omoide Yokocho',
    category: 'activity',
    locationName: 'Kabukicho',
    locationAddress: 'Kabukicho, Shinjuku City, Tokyo',
    locationAddressJp: null,
    locationLat: 35.6951,
    locationLng: 139.7036,
    googleMapsUrl: 'https://maps.google.com/?q=Kabukicho+Shinjuku',
    websiteUrl: null,
    description: 'Neon entertainment district, Godzilla Road, Hotel Gracery Godzilla head. Omoide Yokocho for yakitori. Golden Gai nearby.',
    tips: 'Omoide Yokocho = yakitori alley, great for dinner. Golden Gai is more adult-oriented.',
    whatToOrder: 'Yakitori skewers at Omoide Yokocho',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 4: Tuesday, March 10 - Tokyo Day 3
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 4,
    date: '2026-03-10',
    startTime: '09:00',
    durationMinutes: 180,
    name: 'Imperial Palace East Gardens',
    category: 'temple',
    locationName: 'Imperial Palace East Gardens',
    locationAddress: '1-1 Chiyoda, Chiyoda City, Tokyo',
    locationAddressJp: '〒100-8111 東京都千代田区千代田1-1',
    locationLat: 35.6852,
    locationLng: 139.7528,
    googleMapsUrl: 'https://maps.google.com/?q=Imperial+Palace+East+Gardens',
    websiteUrl: null,
    description: 'Free entry, beautiful gardens. Ninomaru Garden - traditional Japanese garden.',
    tips: 'Free admission. Closed Mondays and Fridays. Opens 9 AM.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 4,
    date: '2026-03-10',
    startTime: '12:00',
    durationMinutes: 300,
    name: 'Yanaka - Old Tokyo',
    category: 'shopping',
    locationName: 'Yanaka Ginza',
    locationAddress: 'Yanaka, Taito City, Tokyo',
    locationAddressJp: null,
    locationLat: 35.7275,
    locationLng: 139.7631,
    googleMapsUrl: 'https://maps.google.com/?q=Yanaka+Ginza',
    websiteUrl: null,
    description: "Old Tokyo shopping street. Cats! Handmade goods. Torino Iru Cafe (birds), Yadorigi Cafe (rescue cats). Lunch at Tayori (Mico's recommendation).",
    tips: 'Torino Iru: ¥1,850/hr + ¥300 shoe covers. Yadorigi: Wed-Sun, drink + food required.',
    whatToOrder: 'Lunch at Tayori',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 4,
    date: '2026-03-10',
    startTime: '18:00',
    durationMinutes: 180,
    name: 'Ebisu Evening - Ramen & Izakaya',
    category: 'food',
    locationName: 'Ebisu Yokocho',
    locationAddress: '1-7-4 Ebisunishi, Shibuya City, Tokyo',
    locationAddressJp: null,
    locationLat: 35.6467,
    locationLng: 139.7104,
    googleMapsUrl: 'https://maps.google.com/?q=Ebisu+Yokocho',
    websiteUrl: null,
    description: "Lively izakaya food hall. Afuri Ramen nearby - one of Tokyo's best.",
    tips: 'Afuri is famous for yuzu shio ramen. Ebisu Yokocho has many small food stalls.',
    whatToOrder: 'Yuzu shio ramen at Afuri',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 5: Wednesday, March 11 - Tokyo Day 4 (Ghibli & TeamLab)
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 5,
    date: '2026-03-11',
    startTime: '09:00',
    durationMinutes: 180,
    name: 'Ghibli Museum',
    category: 'activity',
    locationName: 'Ghibli Museum',
    locationAddress: '1-1-83 Shimorenjaku, Mitaka, Tokyo',
    locationAddressJp: '〒181-0013 東京都三鷹市下連雀1-1-83',
    locationLat: 35.6962,
    locationLng: 139.5704,
    googleMapsUrl: 'https://maps.google.com/?q=Ghibli+Museum',
    websiteUrl: 'https://www.ghibli-museum.jp/en/',
    description: 'Magical museum for Studio Ghibli fans. Walk through Inokashira Park to get there.',
    tips: 'TICKETS REQUIRED - buy Feb 10 at 7 PM CST on Lawson Ticket. No photos inside.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 5,
    date: '2026-03-11',
    startTime: '12:00',
    durationMinutes: 180,
    name: 'TeamLab Borderless',
    category: 'activity',
    locationName: 'TeamLab Borderless',
    locationAddress: 'Azabudai Hills Garden Plaza B B1, 5-9 Toranomon, Minato-ku',
    locationAddressJp: null,
    locationLat: 35.6654,
    locationLng: 139.7425,
    googleMapsUrl: 'https://maps.google.com/?q=TeamLab+Borderless+Azabudai',
    websiteUrl: 'https://www.teamlab.art/e/borderless-azabudai/',
    description: 'Immersive digital art museum. Entry 12:00-12:30 PM. Allow 2-3 hours.',
    tips: 'Wear comfortable shoes, avoid white clothes (colors project on you). Charge phone for photos.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 5,
    date: '2026-03-11',
    startTime: '15:30',
    durationMinutes: 60,
    name: 'Oh My Glasses - Eyeglasses for Angie',
    category: 'shopping',
    locationName: 'Oh My Glasses Tokyo Shinjuku East',
    locationAddress: 'Shinjuku, Tokyo',
    locationAddressJp: null,
    locationLat: 35.6917,
    locationLng: 139.7043,
    googleMapsUrl: 'https://maps.app.goo.gl/57uAabM4wCevQCPu8',
    websiteUrl: null,
    description: 'Eyeglasses shopping for Angie.',
    tips: 'Japanese optical shops often have same-day service.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 5,
    date: '2026-03-11',
    startTime: '18:00',
    durationMinutes: 120,
    name: 'Rest & Prepare for Hakone',
    category: 'activity',
    locationName: '&Here Shinjuku',
    locationAddress: 'Shinjuku, Tokyo',
    locationAddressJp: null,
    locationLat: 35.6917,
    locationLng: 139.7043,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Rest and pack for travel day tomorrow. Optional: book cooking class.',
    tips: 'Pack for 2 nights in Hakone. Ryokan provides yukatas.',
    whatToOrder: null,
    backupAlternative: 'Cooking class via airkitchen.me',
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 6: Thursday, March 12 - Tokyo → Hakone
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 6,
    date: '2026-03-12',
    startTime: '08:00',
    durationMinutes: 180,
    name: 'Breakfast & Check-out',
    category: 'hotel',
    locationName: '&Here Shinjuku',
    locationAddress: '2-15-14-2 Shinjuku, Tokyo',
    locationAddressJp: null,
    locationLat: 35.6917,
    locationLng: 139.7043,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Breakfast, final packing, check out by 11 AM.',
    tips: 'Leave time to get to Shinjuku Station.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 6,
    date: '2026-03-12',
    startTime: '11:30',
    durationMinutes: 30,
    name: 'Buy Hakone Free Pass & Romancecar',
    category: 'transit',
    locationName: 'Shinjuku Station - Odakyu',
    locationAddress: 'Shinjuku Station, Tokyo',
    locationAddressJp: null,
    locationLat: 35.6896,
    locationLng: 139.7006,
    googleMapsUrl: 'https://maps.google.com/?q=Shinjuku+Station',
    websiteUrl: null,
    description: 'Purchase Hakone Free Pass (¥7,100 adult) + Romancecar upgrade (¥1,200 one-way).',
    tips: 'Odakyu Sightseeing Service Center at West or South exits. EMot app works too.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 6,
    date: '2026-03-12',
    startTime: '12:00',
    durationMinutes: 80,
    name: 'Romancecar to Hakone-Yumoto',
    category: 'transit',
    locationName: 'Romancecar',
    locationAddress: 'Shinjuku → Hakone-Yumoto',
    locationAddressJp: null,
    locationLat: 35.2318,
    locationLng: 139.1053,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Limited Express with reserved seats, restrooms, Mt. Fuji views. 80 min ride.',
    tips: 'Right side seats have Mt. Fuji views (weather permitting).',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 6,
    date: '2026-03-12',
    startTime: '13:30',
    durationMinutes: 210,
    name: 'Hakone Circuit to Lake Ashi',
    category: 'activity',
    locationName: 'Hakone',
    locationAddress: 'Hakone, Kanagawa',
    locationAddressJp: null,
    locationLat: 35.1907,
    locationLng: 139.0206,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Use Hakone Free Pass. Options: Direct to Lake Ashi area OR do partial Hakone loop.',
    tips: 'All covered by Hakone Free Pass. Allow time to reach Hakonemachi Port by 5 PM.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 6,
    date: '2026-03-12',
    startTime: '17:00',
    durationMinutes: 30,
    name: 'Ryokan Pickup at Hakonemachi Port',
    category: 'hotel',
    locationName: 'Hakonemachi Port Pier',
    locationAddress: 'Hakonemachi Port, Hakone',
    locationAddressJp: null,
    locationLat: 35.1907,
    locationLng: 139.0206,
    googleMapsUrl: 'https://maps.google.com/?q=Hakonemachi+Port',
    websiteUrl: null,
    description: 'CALL AHEAD (0460-83-6661) to arrange pickup. Wait at Pirate Ship landing.',
    tips: 'CRITICAL: Call ryokan before 5 PM to confirm pickup time!',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 6,
    date: '2026-03-12',
    startTime: '18:00',
    durationMinutes: 90,
    name: 'Kaiseki Dinner at Ryokan',
    category: 'food',
    locationName: 'Takumino yado Yoshimatsu',
    locationAddress: '521 Hakone, Hakone-machi',
    locationAddressJp: null,
    locationLat: 35.1907,
    locationLng: 139.0206,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Kyoto-style Kaiseki cuisine served in your room. Multi-course traditional meal.',
    tips: 'Wear yukata (provided). Sit on tatami. Many small courses.',
    whatToOrder: 'Included - multi-course kaiseki',
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 6,
    date: '2026-03-12',
    startTime: '20:00',
    durationMinutes: 60,
    name: 'Onsen (Hot Spring Baths)',
    category: 'activity',
    locationName: 'Takumino yado Yoshimatsu',
    locationAddress: '521 Hakone, Hakone-machi',
    locationAddressJp: null,
    locationLat: 35.1907,
    locationLng: 139.0206,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Outdoor hot spring baths with Mt. Fuji and Lake Ashi views.',
    tips: 'Wash/rinse thoroughly BEFORE entering. Small towel on head, not in water. Enter slowly.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 7: Friday, March 13 - Hakone Full Day
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 7,
    date: '2026-03-13',
    startTime: '07:30',
    durationMinutes: 60,
    name: 'Breakfast at Ryokan',
    category: 'food',
    locationName: 'Takumino yado Yoshimatsu',
    locationAddress: '521 Hakone, Hakone-machi',
    locationAddressJp: null,
    locationLat: 35.1907,
    locationLng: 139.0206,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Japanese set menu breakfast served in room or private dining room.',
    tips: 'Traditional Japanese breakfast - rice, fish, miso soup, pickles.',
    whatToOrder: 'Included - Japanese breakfast set',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 7,
    date: '2026-03-13',
    startTime: '09:00',
    durationMinutes: 60,
    name: 'Pirate Ship Cruise',
    category: 'activity',
    locationName: 'Lake Ashi',
    locationAddress: 'Hakonemachi → Togendai',
    locationAddressJp: null,
    locationLat: 35.2053,
    locationLng: 139.0227,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Scenic 30-min cruise on Lake Ashi. Views of Mt. Fuji and Hakone Shrine torii.',
    tips: 'Covered by Hakone Free Pass. Dress warmly - cold on deck.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 7,
    date: '2026-03-13',
    startTime: '10:00',
    durationMinutes: 90,
    name: 'Owakudani (Hell Valley)',
    category: 'activity',
    locationName: 'Owakudani',
    locationAddress: 'Owakudani, Hakone',
    locationAddressJp: null,
    locationLat: 35.2439,
    locationLng: 139.0247,
    googleMapsUrl: 'https://maps.google.com/?q=Owakudani',
    websiteUrl: null,
    description: 'Volcanic valley with sulfur vents. Famous black eggs (kuro-tamago) - adds 7 years to life! Mt. Fuji views.',
    tips: 'Ropeway from Togendai. 30-min walking trail. Buy black eggs (5 for ¥500).',
    whatToOrder: 'Kuro-tamago (black eggs)',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 7,
    date: '2026-03-13',
    startTime: '12:00',
    durationMinutes: 180,
    name: 'Hakone Open-Air Museum',
    category: 'activity',
    locationName: 'Hakone Open-Air Museum',
    locationAddress: '1121 Ninotaira, Hakone',
    locationAddressJp: null,
    locationLat: 35.2501,
    locationLng: 139.0534,
    googleMapsUrl: 'https://maps.google.com/?q=Hakone+Open+Air+Museum',
    websiteUrl: 'https://www.hakone-oam.or.jp/en/',
    description: 'Outdoor sculpture museum. Picasso Pavilion (300+ works), Symphonic Sculpture (rainbow stained glass tower), Woods of Net climbing structure, foot bath.',
    tips: 'Discount with Hakone Free Pass. Allow 2-3 hours. Kids love the climbing structures.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 7,
    date: '2026-03-13',
    startTime: '15:30',
    durationMinutes: 60,
    name: 'Hakone Shrine',
    category: 'temple',
    locationName: 'Hakone Shrine',
    locationAddress: '80-1 Motohakone, Hakone',
    locationAddressJp: null,
    locationLat: 35.1988,
    locationLng: 139.0281,
    googleMapsUrl: 'https://maps.google.com/?q=Hakone+Shrine',
    websiteUrl: null,
    description: 'Floating red torii gate in the lake. Peaceful forest walk to main shrine.',
    tips: 'Iconic photo spot. Early morning or late afternoon for fewer crowds.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 7,
    date: '2026-03-13',
    startTime: '17:00',
    durationMinutes: 60,
    name: 'Return to Ryokan',
    category: 'hotel',
    locationName: 'Takumino yado Yoshimatsu',
    locationAddress: '521 Hakone, Hakone-machi',
    locationAddressJp: null,
    locationLat: 35.1907,
    locationLng: 139.0206,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Return by bus/walk. Rest before dinner.',
    tips: 'Use bus from Hakone Shrine area back to ryokan.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 7,
    date: '2026-03-13',
    startTime: '18:00',
    durationMinutes: 90,
    name: 'Kaiseki Dinner',
    category: 'food',
    locationName: 'Takumino yado Yoshimatsu',
    locationAddress: '521 Hakone, Hakone-machi',
    locationAddressJp: null,
    locationLat: 35.1907,
    locationLng: 139.0206,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Second night kaiseki dinner in room.',
    tips: 'May be different menu from first night.',
    whatToOrder: 'Included - multi-course kaiseki',
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 7,
    date: '2026-03-13',
    startTime: '20:00',
    durationMinutes: 60,
    name: 'Onsen',
    category: 'activity',
    locationName: 'Takumino yado Yoshimatsu',
    locationAddress: '521 Hakone, Hakone-machi',
    locationAddressJp: null,
    locationLat: 35.1907,
    locationLng: 139.0206,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Evening onsen soak.',
    tips: 'Try different bath than yesterday if available.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 8,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 8: Saturday, March 14 - Hakone → Kyoto
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 8,
    date: '2026-03-14',
    startTime: '07:00',
    durationMinutes: 60,
    name: 'Breakfast at Ryokan',
    category: 'food',
    locationName: 'Takumino yado Yoshimatsu',
    locationAddress: '521 Hakone, Hakone-machi',
    locationAddressJp: null,
    locationLat: 35.1907,
    locationLng: 139.0206,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Final breakfast at ryokan.',
    tips: null,
    whatToOrder: 'Included - Japanese breakfast',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 8,
    date: '2026-03-14',
    startTime: '09:00',
    durationMinutes: 120,
    name: 'Check-out & Drop-off to Port',
    category: 'hotel',
    locationName: 'Takumino yado Yoshimatsu → Hakonemachi Port',
    locationAddress: 'Hakone',
    locationAddressJp: null,
    locationLat: 35.1907,
    locationLng: 139.0206,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Check out by 11 AM. Arrange drop-off (8-11 AM) to Hakonemachi Port.',
    tips: 'Tell front desk your preferred drop-off time (seating limited).',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 8,
    date: '2026-03-14',
    startTime: '11:30',
    durationMinutes: 30,
    name: 'Bus/Train to Odawara Station',
    category: 'transit',
    locationName: 'Hakonemachi → Odawara',
    locationAddress: 'Hakone → Odawara',
    locationAddressJp: null,
    locationLat: 35.2564,
    locationLng: 139.1551,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Take bus to Odawara Station for Shinkansen.',
    tips: 'Hakone Free Pass covers bus. Allow time for luggage.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 8,
    date: '2026-03-14',
    startTime: '12:00',
    durationMinutes: 120,
    name: 'Shinkansen Odawara → Kyoto',
    category: 'transit',
    locationName: 'Shinkansen',
    locationAddress: 'Odawara → Kyoto',
    locationAddressJp: null,
    locationLat: 35.0116,
    locationLng: 135.7681,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Bullet train to Kyoto (~2 hours).',
    tips: 'Reserved seats recommended. Buy ekiben (train bento) for lunch.',
    whatToOrder: 'Ekiben (train bento box)',
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 8,
    date: '2026-03-14',
    startTime: '14:00',
    durationMinutes: 60,
    name: 'Arrive Kyoto & Check-in at Desk',
    category: 'hotel',
    locationName: 'MACHIYA INNS Check-in Desk',
    locationAddress: '685-2 Higashishiokōjichō, Shimogyō-ku, Kyoto',
    locationAddressJp: null,
    locationLat: 34.9857,
    locationLng: 135.7594,
    googleMapsUrl: 'https://g.page/machiya-inns-hotels',
    websiteUrl: null,
    description: 'Go to check-in desk FIRST (not the house). 3-min walk from Kyoto Station. PAY ¥8,400 ACCOMMODATION TAX IN CASH.',
    tips: 'CRITICAL: Bring ¥8,400 cash for tax. Desk hours 10 AM - 7 PM.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 8,
    date: '2026-03-14',
    startTime: '15:30',
    durationMinutes: 30,
    name: 'Walk to Fujinoma Machiya House',
    category: 'hotel',
    locationName: 'Fujinoma Machiya House',
    locationAddress: '476-11 Tenshitsukinuke 4chome, Shimogyo Ward, Kyoto',
    locationAddressJp: '〒600-8456 京都市下京区天使突抜4丁目476-11',
    locationLat: 34.9918,
    locationLng: 135.7534,
    googleMapsUrl: null,
    websiteUrl: 'https://www.kyoto-machiya-inn.com/accommodations/fujinoma/',
    description: 'Receive instructions at desk, then proceed to house. Traditional machiya townhouse.',
    tips: 'Private house - no staff on-site. Use provided instructions.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 8,
    date: '2026-03-14',
    startTime: '17:00',
    durationMinutes: 180,
    name: 'Light Exploration & Easy Dinner',
    category: 'activity',
    locationName: 'Near Machiya',
    locationAddress: 'Kyoto',
    locationAddressJp: null,
    locationLat: 34.9918,
    locationLng: 135.7534,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Rest, explore neighborhood, easy dinner.',
    tips: 'Many restaurants near Kyoto Station.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 9: Sunday, March 15 - Kyoto with Mico
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 9,
    date: '2026-03-15',
    startTime: '09:00',
    durationMinutes: 180,
    name: 'Kiyomizudera Temple',
    category: 'temple',
    locationName: 'Kiyomizudera Temple',
    locationAddress: '1-294 Kiyomizu, Higashiyama Ward, Kyoto',
    locationAddressJp: '〒605-0862 京都市東山区清水1-294',
    locationLat: 35.0030,
    locationLng: 135.7850,
    googleMapsUrl: 'https://maps.google.com/?q=Kiyomizu-dera',
    websiteUrl: null,
    description: 'Famous wooden stage with city views. UNESCO World Heritage Site. With guide Mico.',
    tips: 'Wear comfortable walking shoes. Many stairs.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 9,
    date: '2026-03-15',
    startTime: '12:00',
    durationMinutes: 120,
    name: 'Gion Backstreets & Nishiki Market',
    category: 'shopping',
    locationName: 'Gion & Nishiki Market',
    locationAddress: 'Gion, Kyoto',
    locationAddressJp: null,
    locationLat: 35.0036,
    locationLng: 135.7755,
    googleMapsUrl: 'https://maps.google.com/?q=Nishiki+Market+Kyoto',
    websiteUrl: null,
    description: "Geisha district backstreets. Nishiki Market - 'Kyoto's Kitchen' for lunch and food sampling. 400+ years old.",
    tips: 'Nishiki Market best before 4 PM. Many free samples.',
    whatToOrder: 'Tamagoyaki (rolled omelette), pickles, mochi',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 9,
    date: '2026-03-15',
    startTime: '14:00',
    durationMinutes: 90,
    name: 'Sanjusangendo Temple',
    category: 'temple',
    locationName: 'Sanjusangendo Temple',
    locationAddress: '657 Sanjusangendomawari, Higashiyama Ward, Kyoto',
    locationAddressJp: null,
    locationLat: 34.9876,
    locationLng: 135.7716,
    googleMapsUrl: 'https://maps.google.com/?q=Sanjusangendo',
    websiteUrl: null,
    description: '1,001 golden statues of Kannon. Incredible sight.',
    tips: 'No photos inside. Take time to look at each unique statue.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 9,
    date: '2026-03-15',
    startTime: '16:00',
    durationMinutes: 180,
    name: 'Fushimi Inari',
    category: 'temple',
    locationName: 'Fushimi Inari Taisha',
    locationAddress: '68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto',
    locationAddressJp: null,
    locationLat: 34.9671,
    locationLng: 135.7727,
    googleMapsUrl: 'https://maps.google.com/?q=Fushimi+Inari+Taisha',
    websiteUrl: null,
    description: 'Thousands of orange torii gates. Evening visit = fewer crowds. Full hike is 2-3 hours.',
    tips: 'Evening light is beautiful through torii. Go at least to first viewpoint.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 10: Monday, March 16 - Kyoto Arashiyama
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 10,
    date: '2026-03-16',
    startTime: '09:00',
    durationMinutes: 60,
    name: 'Togetsukyo Bridge & Monkey Park',
    category: 'activity',
    locationName: 'Togetsukyo Bridge',
    locationAddress: 'Arashiyama, Kyoto',
    locationAddressJp: null,
    locationLat: 35.0094,
    locationLng: 135.6785,
    googleMapsUrl: 'https://maps.google.com/?q=Togetsukyo+Bridge',
    websiteUrl: null,
    description: 'Iconic bridge. Iwatayama Monkey Park - 120 wild Japanese macaques with city views.',
    tips: 'Monkey park is uphill walk. Macaques are wild - follow rules.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 10,
    date: '2026-03-16',
    startTime: '10:30',
    durationMinutes: 90,
    name: 'Bamboo Grove & Tenryu-ji Temple',
    category: 'temple',
    locationName: 'Arashiyama Bamboo Grove',
    locationAddress: 'Arashiyama, Kyoto',
    locationAddressJp: null,
    locationLat: 35.0170,
    locationLng: 135.6713,
    googleMapsUrl: 'https://maps.google.com/?q=Arashiyama+Bamboo+Grove',
    websiteUrl: null,
    description: 'Iconic towering bamboo forest path. Tenryu-ji - UNESCO Zen temple with garden.',
    tips: 'Arrive early for fewer crowds. Morning light is best.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 10,
    date: '2026-03-16',
    startTime: '12:00',
    durationMinutes: 60,
    name: 'Lunch in Arashiyama',
    category: 'food',
    locationName: 'Arashiyama',
    locationAddress: 'Arashiyama, Kyoto',
    locationAddressJp: null,
    locationLat: 35.0094,
    locationLng: 135.6785,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Lunch in Arashiyama area.',
    tips: 'Many restaurants along main street. Try local tofu dishes.',
    whatToOrder: 'Yudofu (hot tofu), soba',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 10,
    date: '2026-03-16',
    startTime: '13:00',
    durationMinutes: 120,
    name: '2-Hour Rickshaw Ride',
    category: 'activity',
    locationName: 'Arashiyama',
    locationAddress: 'Arashiyama, Kyoto',
    locationAddressJp: null,
    locationLat: 35.0094,
    locationLng: 135.6785,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'May include Jojakku-ji, Gioji temples, Adashino Nenbutsu-ji.',
    tips: 'Rickshaw pullers are knowledgeable guides. Book in advance if possible.',
    whatToOrder: null,
    backupAlternative: 'Walk the area instead',
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 10,
    date: '2026-03-16',
    startTime: '16:00',
    durationMinutes: 90,
    name: 'Kinkaku-ji (Golden Pavilion)',
    category: 'temple',
    locationName: 'Kinkaku-ji',
    locationAddress: '1 Kinkakujicho, Kita Ward, Kyoto',
    locationAddressJp: null,
    locationLat: 35.0394,
    locationLng: 135.7292,
    googleMapsUrl: 'https://maps.google.com/?q=Kinkaku-ji',
    websiteUrl: null,
    description: 'Golden Pavilion - Zen temple covered in gold leaf.',
    tips: 'Late afternoon light is beautiful on the gold. Less crowded than morning.',
    whatToOrder: null,
    backupAlternative: 'Do this Day 11 morning if running late',
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 10,
    date: '2026-03-16',
    startTime: '18:30',
    durationMinutes: 120,
    name: 'Pontocho Alley Dinner',
    category: 'food',
    locationName: 'Pontocho',
    locationAddress: 'Pontocho, Kyoto',
    locationAddressJp: null,
    locationLat: 35.0057,
    locationLng: 135.7706,
    googleMapsUrl: 'https://maps.google.com/?q=Pontocho+Kyoto',
    websiteUrl: null,
    description: 'Atmospheric lantern-lit dining street along the river.',
    tips: 'Many restaurants have riverside seating in summer. Very romantic at night.',
    whatToOrder: 'Kaiseki, yakitori, or izakaya food',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 10,
    date: '2026-03-16',
    startTime: '20:30',
    durationMinutes: 30,
    name: 'Dessert Stop',
    category: 'food',
    locationName: 'Atelier Pages or Pre-Marche Gelateria',
    locationAddress: 'Kyoto',
    locationAddressJp: null,
    locationLat: 35.0036,
    locationLng: 135.7755,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Atelier Pages - beautiful French cakes. Pre-Marche Gelateria - 40+ flavors.',
    tips: 'Try yuzu or sesame gelato at Pre-Marche.',
    whatToOrder: 'Seasonal tart, yuzu gelato',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 11: Tuesday, March 17 - Kyoto → Osaka
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 11,
    date: '2026-03-17',
    startTime: '09:00',
    durationMinutes: 60,
    name: 'Breakfast & Pack Up',
    category: 'hotel',
    locationName: 'Fujinoma Machiya',
    locationAddress: 'Kyoto',
    locationAddressJp: null,
    locationLat: 34.9918,
    locationLng: 135.7534,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Breakfast, pack up. Check out by 10 AM.',
    tips: 'Leave luggage at check-in desk if needed (10 AM - 7 PM).',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 11,
    date: '2026-03-17',
    startTime: '10:30',
    durationMinutes: 90,
    name: 'Optional: Golden Pavilion or Shopping',
    category: 'activity',
    locationName: 'Kyoto',
    locationAddress: 'Kyoto',
    locationAddressJp: null,
    locationLat: 35.0116,
    locationLng: 135.7681,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Visit anything missed (Golden Pavilion if not done). Or explore Kyoto Station area.',
    tips: null,
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 11,
    date: '2026-03-17',
    startTime: '12:00',
    durationMinutes: 45,
    name: 'Train to Osaka',
    category: 'transit',
    locationName: 'JR Special Rapid',
    locationAddress: 'Kyoto → Osaka',
    locationAddressJp: null,
    locationLat: 34.7024,
    locationLng: 135.4959,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'JR Special Rapid from Kyoto Station → Osaka Station (29 min, ¥560). Then subway to Shinsaibashi.',
    tips: 'Frequent trains. Transfer to Midosuji Line for Shinsaibashi.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 11,
    date: '2026-03-17',
    startTime: '13:00',
    durationMinutes: 120,
    name: 'Arrive Osaka & Lunch',
    category: 'food',
    locationName: 'Osaka',
    locationAddress: 'Osaka',
    locationAddressJp: null,
    locationLat: 34.6724,
    locationLng: 135.5023,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Arrive Osaka, find lunch near station or Shinsaibashi.',
    tips: 'Osaka is famous for takoyaki (octopus balls) and okonomiyaki (savory pancakes).',
    whatToOrder: 'Takoyaki, okonomiyaki',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 11,
    date: '2026-03-17',
    startTime: '15:00',
    durationMinutes: 60,
    name: 'Check-in at MIMARU',
    category: 'hotel',
    locationName: 'MIMARU Osaka Shinsaibashi East',
    locationAddress: '1-7-9 Higashishinsaibashi, Chuo-ku, Osaka',
    locationAddressJp: '〒542-0083 大阪市中央区東心斎橋1-7-9',
    locationLat: 34.6724,
    locationLng: 135.5023,
    googleMapsUrl: 'https://maps.google.com/?q=MIMARU+Osaka+Shinsaibashi+East',
    websiteUrl: 'https://mimaruhotels.com/en/hotel/shinsaibashi-east/',
    description: 'Check-in 3-10 PM. Confirmation: 5937762447, PIN: 7761. FULLY PAID.',
    tips: 'Walking distance to Dotonbori.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 11,
    date: '2026-03-17',
    startTime: '16:30',
    durationMinutes: 150,
    name: 'Shinsaibashi Shopping',
    category: 'shopping',
    locationName: 'Shinsaibashi',
    locationAddress: 'Shinsaibashi, Osaka',
    locationAddressJp: null,
    locationLat: 34.6750,
    locationLng: 135.5013,
    googleMapsUrl: 'https://maps.google.com/?q=Shinsaibashi+Osaka',
    websiteUrl: null,
    description: 'Rest, then light shopping in Shinsaibashi shopping arcade.',
    tips: 'Covered arcade - good even if raining.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 11,
    date: '2026-03-17',
    startTime: '19:00',
    durationMinutes: 180,
    name: 'Dotonbori Evening',
    category: 'activity',
    locationName: 'Dotonbori',
    locationAddress: 'Dotonbori, Osaka',
    locationAddressJp: null,
    locationLat: 34.6687,
    locationLng: 135.5018,
    googleMapsUrl: 'https://maps.google.com/?q=Dotonbori+Osaka',
    websiteUrl: null,
    description: 'Glico Running Man sign, Ebisu Bridge, Hozenji Yokocho alley. Hanamaruken for pork rib ramen.',
    tips: 'Neon signs are best after dark. Ebisu Bridge is best photo spot.',
    whatToOrder: 'Pork rib ramen at Hanamaruken',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 12: Wednesday, March 18 - Osaka with Mico
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 12,
    date: '2026-03-18',
    startTime: '09:00',
    durationMinutes: 180,
    name: 'Kuromon Market with Mico',
    category: 'shopping',
    locationName: 'Kuromon Market',
    locationAddress: 'Kuromon Market, Osaka',
    locationAddressJp: null,
    locationLat: 34.6678,
    locationLng: 135.5057,
    googleMapsUrl: 'https://maps.google.com/?q=Kuromon+Market+Osaka',
    websiteUrl: null,
    description: "Osaka's Kitchen - 200+ years old, 150+ shops. Seafood, wagyu, street snacks.",
    tips: 'Arrive before lunch for freshest food. Many vendors let you try samples.',
    whatToOrder: 'Fresh sashimi, grilled wagyu, tamagoyaki',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 12,
    date: '2026-03-18',
    startTime: '12:00',
    durationMinutes: 240,
    name: 'Food Tour with Mico',
    category: 'food',
    locationName: 'Osaka Hidden Spots',
    locationAddress: 'Various, Osaka',
    locationAddressJp: null,
    locationLat: 34.6937,
    locationLng: 135.5023,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Knife shop demo, hidden alleys, sake samplings, local spots tourists miss, "underworld" visit.',
    tips: '5-7 hour tour with Mico. Wear comfortable shoes.',
    whatToOrder: 'Whatever Mico recommends!',
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 12,
    date: '2026-03-18',
    startTime: '18:00',
    durationMinutes: 180,
    name: 'Rest & Dinner',
    category: 'food',
    locationName: 'MIMARU / Nearby',
    locationAddress: 'Shinsaibashi, Osaka',
    locationAddressJp: null,
    locationLat: 34.6724,
    locationLng: 135.5023,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Rest after long food tour. Light dinner or cook at apartment.',
    tips: 'MIMARU has kitchen - good for light cooking.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 13: Thursday, March 19 - Kyoto Mountain Day Trip
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 13,
    date: '2026-03-19',
    startTime: '08:00',
    durationMinutes: 720,
    name: 'Full Day Mountain Tour with Mico + Driver',
    category: 'activity',
    locationName: 'Kyoto Mountains',
    locationAddress: 'North Kyoto Prefecture',
    locationAddressJp: null,
    locationLat: 35.4700,
    locationLng: 135.2200,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Kayabuki no Sato (thatched-roof village), Shaga Forest ("no tourist has ever been"), Ine Village (fishing funaya boat houses), Amanohashidate (one of Japan\'s Three Views), Nara Primeval Forest (ancient carvings). Forest bathing, waterfalls.',
    tips: 'Long day with driving. Bring snacks, camera, comfortable clothes. Pack layers.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 13,
    date: '2026-03-19',
    startTime: '20:00',
    durationMinutes: 120,
    name: 'Return & Dinner',
    category: 'food',
    locationName: 'Osaka',
    locationAddress: 'Shinsaibashi area',
    locationAddressJp: null,
    locationLat: 34.6724,
    locationLng: 135.5023,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Return to Osaka late. Light dinner.',
    tips: 'Convenience stores or nearby restaurants.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 14: Friday, March 20 - Nara & Sumo (Emma's Birthday!)
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 14,
    date: '2026-03-20',
    startTime: '09:00',
    durationMinutes: 300,
    name: 'Nara Day Trip',
    category: 'activity',
    locationName: 'Nara Park & Todai-ji',
    locationAddress: 'Nara, Japan',
    locationAddressJp: null,
    locationLat: 34.6851,
    locationLng: 135.8050,
    googleMapsUrl: 'https://maps.google.com/?q=Nara+Park',
    websiteUrl: null,
    description: "Nara Park - 1,200+ friendly wild deer. Todai-ji Temple - world's largest bronze Buddha. Buy shika senbei (deer crackers) to feed deer. Lunch in Nara. Return by ~2 PM.",
    tips: 'Deer are friendly but can be pushy. Hide food wrappers. Watch kids around deer.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 14,
    date: '2026-03-20',
    startTime: '14:30',
    durationMinutes: 210,
    name: 'Osaka Sumo Tournament',
    category: 'activity',
    locationName: 'EDION Arena Osaka',
    locationAddress: 'Near Namba Station, Osaka',
    locationAddressJp: null,
    locationLat: 34.6587,
    locationLng: 135.4997,
    googleMapsUrl: 'https://maps.google.com/?q=EDION+Arena+Osaka',
    websiteUrl: 'https://sumo.pia.jp/en/sumo03.jsp',
    description: 'March Tournament! Top-division matches ~3 PM, ends ~6 PM. Buy tickets Feb 6 at 7 PM CST.',
    tips: 'TICKETS REQUIRED - buy Feb 6. March 20 doors open 10:30 AM. Can exit/re-enter once before 5 PM.',
    whatToOrder: null,
    backupAlternative: 'If no tickets: Himeji Castle day trip OR shopping day',
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 14,
    date: '2026-03-20',
    startTime: '18:30',
    durationMinutes: 150,
    name: "Emma's Birthday Dinner",
    category: 'food',
    locationName: 'TBD - Ask Mico',
    locationAddress: 'Osaka',
    locationAddressJp: null,
    locationLat: 34.6937,
    locationLng: 135.5023,
    googleMapsUrl: null,
    websiteUrl: null,
    description: "Special last dinner in Japan. Celebrate Emma's 10th birthday!",
    tips: "Ask Mico for recommendation. Somewhere special for Emma's big day!",
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },

  // -------------------------------------------------------------------------
  // Day 15: Saturday, March 21 - Departure Day
  // -------------------------------------------------------------------------
  {
    id: genId('act'),
    dayNumber: 15,
    date: '2026-03-21',
    startTime: '08:00',
    durationMinutes: 180,
    name: 'Breakfast & Check-out',
    category: 'hotel',
    locationName: 'MIMARU Osaka',
    locationAddress: '1-7-9 Higashishinsaibashi, Osaka',
    locationAddressJp: null,
    locationLat: 34.6724,
    locationLng: 135.5023,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Final breakfast, check out by 11 AM. Can leave luggage at hotel.',
    tips: 'Check out early to have time for shopping before train.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 15,
    date: '2026-03-21',
    startTime: '10:00',
    durationMinutes: 150,
    name: 'Shinkansen to Tokyo',
    category: 'transit',
    locationName: 'Shinkansen Nozomi',
    locationAddress: 'Shin-Osaka → Tokyo',
    locationAddressJp: null,
    locationLat: 35.6812,
    locationLng: 139.7671,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Shinkansen from Shin-Osaka to Tokyo (~2.5 hours). Arrive ~12:30 PM.',
    tips: 'Reserved seats recommended. Buy lunch at Shin-Osaka Station.',
    whatToOrder: 'Ekiben (train bento)',
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 15,
    date: '2026-03-21',
    startTime: '12:30',
    durationMinutes: 120,
    name: 'Optional Quick Shopping',
    category: 'shopping',
    locationName: 'Tokyo',
    locationAddress: 'Shinjuku or Akihabara',
    locationAddressJp: null,
    locationLat: 35.6812,
    locationLng: 139.7671,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Optional last-minute shopping if time allows.',
    tips: 'Keep track of time - need to be at airport by 3:30 PM.',
    whatToOrder: null,
    backupAlternative: 'Skip and go straight to airport',
    isHardDeadline: false,
    isKidFriendly: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 15,
    date: '2026-03-21',
    startTime: '15:00',
    durationMinutes: 30,
    name: 'Train to Haneda Airport',
    category: 'transit',
    locationName: 'To Haneda Terminal 3',
    locationAddress: 'Tokyo → Haneda',
    locationAddressJp: null,
    locationLat: 35.5494,
    locationLng: 139.7798,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Train to Haneda Airport. Arrive by 3:30 PM for 5:20 PM flight.',
    tips: 'Allow 2 hours before flight for international departure.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: genId('act'),
    dayNumber: 15,
    date: '2026-03-21',
    startTime: '17:20',
    durationMinutes: 675,
    name: 'Flight DL0120 Home',
    category: 'transit',
    locationName: 'Haneda Airport Terminal 3',
    locationAddress: 'Haneda Airport, Tokyo',
    locationAddressJp: null,
    locationLat: 35.5494,
    locationLng: 139.7798,
    googleMapsUrl: null,
    websiteUrl: null,
    description: 'Flight DL0120 departs 5:20 PM. Arrives Minneapolis 2:35 PM same day (11h 15m).',
    tips: 'You arrive before you left! Time zone magic.',
    whatToOrder: null,
    backupAlternative: null,
    isHardDeadline: true,
    isKidFriendly: true,
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
];

// Reset ID counter for transit segments
idCounter = 0;

// ============================================================================
// TRANSIT SEGMENTS (Leave-by times for key activities)
// ============================================================================

export const transitSegments: TransitSegment[] = [
  // Day 2: To Asakusa
  {
    id: genId('transit'),
    activityId: 'act-0006', // Asakusa activity
    leaveBy: '08:15',
    walkToStationMinutes: 10,
    stationName: 'Shinjuku-sanchome',
    trainLine: 'Tokyo Metro Marunouchi → Asakusa',
    suggestedDeparture: '08:25',
    travelMinutes: 35,
    transfers: 'Transfer at Akasaka-mitsuke',
    arrivalStation: 'Asakusa',
    walkToDestinationMinutes: 5,
    bufferMinutes: 10,
    steps: [
      { type: 'walk', instruction: 'Walk to Shinjuku-sanchome Station', duration: 10 },
      { type: 'train', instruction: 'Take Marunouchi Line to Akasaka-mitsuke', duration: 15, departure: '08:25' },
      { type: 'transfer', instruction: 'Transfer to Ginza Line', duration: 5 },
      { type: 'train', instruction: 'Take Ginza Line to Asakusa', duration: 15, departure: '08:45' },
      { type: 'walk', instruction: 'Walk to Senso-ji Temple', duration: 5 },
    ],
    createdAt: now,
    updatedAt: now,
  },
  // Day 6: To Shinjuku Station for Romancecar
  {
    id: genId('transit'),
    activityId: 'act-0020', // Buy Hakone Free Pass
    leaveBy: '11:00',
    walkToStationMinutes: 15,
    stationName: 'Shinjuku Station',
    trainLine: 'Walk from &Here Shinjuku',
    suggestedDeparture: null,
    travelMinutes: 15,
    transfers: null,
    arrivalStation: 'Shinjuku Station Odakyu',
    walkToDestinationMinutes: 5,
    bufferMinutes: 15,
    steps: [
      { type: 'walk', instruction: 'Walk to Shinjuku Station Odakyu side', duration: 15 },
      { type: 'walk', instruction: 'Find Odakyu Sightseeing Service Center', duration: 5 },
    ],
    createdAt: now,
    updatedAt: now,
  },
];
