import type { Phrase } from '@/types/database';

/**
 * Japanese phrases organized by category
 * Each phrase includes Japanese text, romaji pronunciation, English meaning, and usage context
 */

const now = new Date().toISOString();

export const PHRASES: Phrase[] = [
  // ============================================================================
  // RESTAURANT - ordering, allergies, party size, payment, compliments
  // ============================================================================
  {
    id: 'phrase-restaurant-1',
    category: 'restaurant',
    japanese: 'すみません',
    romaji: 'Sumimasen',
    meaning: 'Excuse me',
    when: 'Getting staff attention',
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-restaurant-2',
    category: 'restaurant',
    japanese: '～人です',
    romaji: '~ nin desu',
    meaning: 'We are [number] people',
    when: 'Telling party size (e.g., "San nin desu" = 3 people)',
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-restaurant-3',
    category: 'restaurant',
    japanese: 'メニューをください',
    romaji: 'Menyuu o kudasai',
    meaning: 'Menu please',
    when: 'Requesting a menu',
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-restaurant-4',
    category: 'restaurant',
    japanese: 'これをください',
    romaji: 'Kore o kudasai',
    meaning: 'This one please',
    when: 'Pointing at menu item to order',
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-restaurant-5',
    category: 'restaurant',
    japanese: 'おすすめは何ですか？',
    romaji: 'Osusume wa nan desu ka?',
    meaning: 'What do you recommend?',
    when: 'Asking for recommendations',
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-restaurant-6',
    category: 'restaurant',
    japanese: 'アレルギーがあります',
    romaji: 'Arerugii ga arimasu',
    meaning: 'I have an allergy',
    when: 'Informing about food allergies',
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-restaurant-7',
    category: 'restaurant',
    japanese: '～は入っていますか？',
    romaji: '~ wa haitte imasu ka?',
    meaning: 'Does this contain ~?',
    when: 'Asking about ingredients (nuts, shellfish, etc.)',
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-restaurant-8',
    category: 'restaurant',
    japanese: 'お会計をお願いします',
    romaji: 'Okaikei o onegai shimasu',
    meaning: 'Check please',
    when: 'Requesting the bill',
    sortOrder: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-restaurant-9',
    category: 'restaurant',
    japanese: 'カードは使えますか？',
    romaji: 'Kaado wa tsukaemasu ka?',
    meaning: 'Can I use a card?',
    when: 'Asking about card payment',
    sortOrder: 9,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-restaurant-10',
    category: 'restaurant',
    japanese: 'とても美味しいです',
    romaji: 'Totemo oishii desu',
    meaning: 'It\'s very delicious',
    when: 'Complimenting the food',
    sortOrder: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-restaurant-11',
    category: 'restaurant',
    japanese: 'ごちそうさまでした',
    romaji: 'Gochisousama deshita',
    meaning: 'Thank you for the meal',
    when: 'After finishing eating (very polite)',
    sortOrder: 11,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-restaurant-12',
    category: 'restaurant',
    japanese: 'お水をください',
    romaji: 'Omizu o kudasai',
    meaning: 'Water please',
    when: 'Requesting water',
    sortOrder: 12,
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================================
  // TRANSIT - directions, platforms, confirmation
  // ============================================================================
  {
    id: 'phrase-transit-1',
    category: 'transit',
    japanese: '～駅はどこですか？',
    romaji: '~ eki wa doko desu ka?',
    meaning: 'Where is ~ station?',
    when: 'Asking for station location',
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-transit-2',
    category: 'transit',
    japanese: '～行きはどのホームですか？',
    romaji: '~ iki wa dono hoomu desu ka?',
    meaning: 'Which platform for ~?',
    when: 'Finding the right platform',
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-transit-3',
    category: 'transit',
    japanese: 'この電車は～に止まりますか？',
    romaji: 'Kono densha wa ~ ni tomarimasu ka?',
    meaning: 'Does this train stop at ~?',
    when: 'Confirming train stops',
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-transit-4',
    category: 'transit',
    japanese: '次は何駅ですか？',
    romaji: 'Tsugi wa nani eki desu ka?',
    meaning: 'What is the next station?',
    when: 'Checking current location',
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-transit-5',
    category: 'transit',
    japanese: '乗り換えはどこですか？',
    romaji: 'Norikae wa doko desu ka?',
    meaning: 'Where do I transfer?',
    when: 'Finding transfer point',
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-transit-6',
    category: 'transit',
    japanese: '～まで何分かかりますか？',
    romaji: '~ made nan pun kakarimasu ka?',
    meaning: 'How many minutes to ~?',
    when: 'Asking travel time',
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-transit-7',
    category: 'transit',
    japanese: '出口はどこですか？',
    romaji: 'Deguchi wa doko desu ka?',
    meaning: 'Where is the exit?',
    when: 'Finding station exit',
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-transit-8',
    category: 'transit',
    japanese: 'ICカードをチャージしたいです',
    romaji: 'IC kaado o chaaji shitai desu',
    meaning: 'I want to charge my IC card',
    when: 'Reloading Suica/Pasmo',
    sortOrder: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-transit-9',
    category: 'transit',
    japanese: 'タクシー乗り場はどこですか？',
    romaji: 'Takushii noriba wa doko desu ka?',
    meaning: 'Where is the taxi stand?',
    when: 'Finding taxi pickup',
    sortOrder: 9,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-transit-10',
    category: 'transit',
    japanese: 'ここで降ります',
    romaji: 'Koko de orimasu',
    meaning: 'I\'ll get off here',
    when: 'Telling taxi driver to stop',
    sortOrder: 10,
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================================
  // SHOPPING - price, sizes, payment
  // ============================================================================
  {
    id: 'phrase-shopping-1',
    category: 'shopping',
    japanese: 'いくらですか？',
    romaji: 'Ikura desu ka?',
    meaning: 'How much is it?',
    when: 'Asking the price',
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-shopping-2',
    category: 'shopping',
    japanese: '見ているだけです',
    romaji: 'Mite iru dake desu',
    meaning: 'Just looking',
    when: 'When staff asks if you need help',
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-shopping-3',
    category: 'shopping',
    japanese: '試着してもいいですか？',
    romaji: 'Shichaku shite mo ii desu ka?',
    meaning: 'May I try this on?',
    when: 'Asking to use fitting room',
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-shopping-4',
    category: 'shopping',
    japanese: '他のサイズはありますか？',
    romaji: 'Hoka no saizu wa arimasu ka?',
    meaning: 'Do you have other sizes?',
    when: 'Asking for different size',
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-shopping-5',
    category: 'shopping',
    japanese: '他の色はありますか？',
    romaji: 'Hoka no iro wa arimasu ka?',
    meaning: 'Do you have other colors?',
    when: 'Asking for different color',
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-shopping-6',
    category: 'shopping',
    japanese: 'これをください',
    romaji: 'Kore o kudasai',
    meaning: 'I\'ll take this',
    when: 'Ready to purchase',
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-shopping-7',
    category: 'shopping',
    japanese: '免税できますか？',
    romaji: 'Menzei dekimasu ka?',
    meaning: 'Is tax-free available?',
    when: 'Asking about tax-free shopping',
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-shopping-8',
    category: 'shopping',
    japanese: '袋をお願いします',
    romaji: 'Fukuro o onegai shimasu',
    meaning: 'A bag please',
    when: 'Requesting shopping bag',
    sortOrder: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-shopping-9',
    category: 'shopping',
    japanese: 'プレゼント用に包んでください',
    romaji: 'Purezento you ni tsutsunde kudasai',
    meaning: 'Please gift wrap it',
    when: 'Requesting gift wrapping',
    sortOrder: 9,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-shopping-10',
    category: 'shopping',
    japanese: 'レシートをください',
    romaji: 'Reshiito o kudasai',
    meaning: 'Receipt please',
    when: 'Requesting receipt',
    sortOrder: 10,
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================================
  // TEMPLE - etiquette, photos, greetings
  // ============================================================================
  {
    id: 'phrase-temple-1',
    category: 'temple',
    japanese: '写真を撮ってもいいですか？',
    romaji: 'Shashin o totte mo ii desu ka?',
    meaning: 'May I take photos?',
    when: 'Asking permission to photograph',
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-temple-2',
    category: 'temple',
    japanese: '靴を脱ぎますか？',
    romaji: 'Kutsu o nugimasu ka?',
    meaning: 'Should I remove my shoes?',
    when: 'Entering temple buildings',
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-temple-3',
    category: 'temple',
    japanese: 'お参りの仕方を教えてください',
    romaji: 'Omairi no shikata o oshiete kudasai',
    meaning: 'Please teach me how to pray',
    when: 'Learning proper prayer etiquette',
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-temple-4',
    category: 'temple',
    japanese: 'おみくじはどこですか？',
    romaji: 'Omikuji wa doko desu ka?',
    meaning: 'Where are the fortune slips?',
    when: 'Finding omikuji',
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-temple-5',
    category: 'temple',
    japanese: 'お守りをください',
    romaji: 'Omamori o kudasai',
    meaning: 'A charm please',
    when: 'Buying protective amulet',
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-temple-6',
    category: 'temple',
    japanese: '御朱印をお願いします',
    romaji: 'Goshuin o onegai shimasu',
    meaning: 'Temple stamp please',
    when: 'Getting temple/shrine stamp',
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-temple-7',
    category: 'temple',
    japanese: '拝観料はいくらですか？',
    romaji: 'Haikanryou wa ikura desu ka?',
    meaning: 'How much is the admission?',
    when: 'Asking entrance fee',
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-temple-8',
    category: 'temple',
    japanese: '閉まる時間は何時ですか？',
    romaji: 'Shimaru jikan wa nanji desu ka?',
    meaning: 'What time does it close?',
    when: 'Checking closing time',
    sortOrder: 8,
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================================
  // HOTEL - reservations, breakfast, checkout
  // ============================================================================
  {
    id: 'phrase-hotel-1',
    category: 'hotel',
    japanese: '予約があります',
    romaji: 'Yoyaku ga arimasu',
    meaning: 'I have a reservation',
    when: 'Checking in',
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-hotel-2',
    category: 'hotel',
    japanese: 'チェックインをお願いします',
    romaji: 'Chekku in o onegai shimasu',
    meaning: 'Check-in please',
    when: 'At front desk',
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-hotel-3',
    category: 'hotel',
    japanese: '朝食は何時からですか？',
    romaji: 'Choushoku wa nanji kara desu ka?',
    meaning: 'What time is breakfast?',
    when: 'Asking breakfast hours',
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-hotel-4',
    category: 'hotel',
    japanese: 'Wi-Fiのパスワードは？',
    romaji: 'Waifai no pasuwaado wa?',
    meaning: 'What\'s the Wi-Fi password?',
    when: 'Getting internet access',
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-hotel-5',
    category: 'hotel',
    japanese: '荷物を預けられますか？',
    romaji: 'Nimotsu o azukeraremasu ka?',
    meaning: 'Can I leave my luggage?',
    when: 'Storing bags before/after checkout',
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-hotel-6',
    category: 'hotel',
    japanese: 'チェックアウトをお願いします',
    romaji: 'Chekku auto o onegai shimasu',
    meaning: 'Check-out please',
    when: 'Leaving the hotel',
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-hotel-7',
    category: 'hotel',
    japanese: 'タオルをもう一枚ください',
    romaji: 'Taoru o mou ichimai kudasai',
    meaning: 'One more towel please',
    when: 'Requesting extra towel',
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-hotel-8',
    category: 'hotel',
    japanese: 'エアコンの使い方を教えてください',
    romaji: 'Eakon no tsukaikata o oshiete kudasai',
    meaning: 'How do I use the AC?',
    when: 'Learning room controls',
    sortOrder: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-hotel-9',
    category: 'hotel',
    japanese: '近くにコンビニはありますか？',
    romaji: 'Chikaku ni konbini wa arimasu ka?',
    meaning: 'Is there a convenience store nearby?',
    when: 'Finding nearby konbini',
    sortOrder: 9,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-hotel-10',
    category: 'hotel',
    japanese: 'タクシーを呼んでください',
    romaji: 'Takushii o yonde kudasai',
    meaning: 'Please call a taxi',
    when: 'Requesting taxi from hotel',
    sortOrder: 10,
    createdAt: now,
    updatedAt: now,
  },

  // ============================================================================
  // EMERGENCY - help, medical, lost items
  // ============================================================================
  {
    id: 'phrase-emergency-1',
    category: 'emergency',
    japanese: '助けてください',
    romaji: 'Tasukete kudasai',
    meaning: 'Please help me',
    when: 'Asking for help',
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-emergency-2',
    category: 'emergency',
    japanese: '警察を呼んでください',
    romaji: 'Keisatsu o yonde kudasai',
    meaning: 'Please call the police',
    when: 'Emergency requiring police',
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-emergency-3',
    category: 'emergency',
    japanese: '救急車を呼んでください',
    romaji: 'Kyuukyuusha o yonde kudasai',
    meaning: 'Please call an ambulance',
    when: 'Medical emergency',
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-emergency-4',
    category: 'emergency',
    japanese: '病院はどこですか？',
    romaji: 'Byouin wa doko desu ka?',
    meaning: 'Where is the hospital?',
    when: 'Finding medical care',
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-emergency-5',
    category: 'emergency',
    japanese: '薬局はどこですか？',
    romaji: 'Yakkyoku wa doko desu ka?',
    meaning: 'Where is the pharmacy?',
    when: 'Finding medication',
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-emergency-6',
    category: 'emergency',
    japanese: '具合が悪いです',
    romaji: 'Guai ga warui desu',
    meaning: 'I feel sick',
    when: 'Describing illness',
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-emergency-7',
    category: 'emergency',
    japanese: '～をなくしました',
    romaji: '~ o nakushimashita',
    meaning: 'I lost my ~',
    when: 'Reporting lost item (wallet, phone, etc.)',
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-emergency-8',
    category: 'emergency',
    japanese: '財布を盗まれました',
    romaji: 'Saifu o nusumaremashita',
    meaning: 'My wallet was stolen',
    when: 'Reporting theft',
    sortOrder: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-emergency-9',
    category: 'emergency',
    japanese: '道に迷いました',
    romaji: 'Michi ni mayoimashita',
    meaning: 'I\'m lost',
    when: 'When you can\'t find your way',
    sortOrder: 9,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'phrase-emergency-10',
    category: 'emergency',
    japanese: '英語を話せる人はいますか？',
    romaji: 'Eigo o hanaseru hito wa imasu ka?',
    meaning: 'Is there someone who speaks English?',
    when: 'Requesting English speaker',
    sortOrder: 10,
    createdAt: now,
    updatedAt: now,
  },
];

/**
 * Phrase categories for filtering
 */
export const PHRASE_CATEGORIES = [
  { id: 'restaurant', label: 'Restaurant', icon: '🍜' },
  { id: 'transit', label: 'Transit', icon: '🚃' },
  { id: 'shopping', label: 'Shopping', icon: '🛍️' },
  { id: 'temple', label: 'Temple', icon: '⛩️' },
  { id: 'hotel', label: 'Hotel', icon: '🏨' },
  { id: 'emergency', label: 'Emergency', icon: '🆘' },
] as const;

export type PhraseCategory = (typeof PHRASE_CATEGORIES)[number]['id'];
